export default () => ({
  app: {
    port: parseInt(process.env.PORT || '3000', 10),
    nodeEnv: process.env.NODE_ENV || 'development',
    apiPrefix: process.env.API_PREFIX || 'api',
    db_host: process.env.DB_HOST || 'localhost',
    db_port: parseInt(process.env.DB_PORT || '3306', 10),
    db_name: process.env.DB_NAME || 'database',
    db_username: process.env.DB_USERNAME || 'root',
    db_password: process.env.DB_PASSWORD || '',
    db_synchronize: process.env.DB_SYNCHRONIZE !== 'false',
    db_logging: process.env.DB_LOGGING === 'true',
    jwt_secret_key: process.env.JWT_SECRET_KEY || 'your-secret-key',
    jwt_expiration_time: process.env.JWT_EXPIRATION_TIME || '1y',
    throttle_ttl: parseInt(process.env.THROTTLE_TTL || '60', 10),
    throttle_limit: parseInt(process.env.THROTTLE_LIMIT || '10', 10),
    cors_origin: process.env.CORS_ORIGIN || '*',
    slack_token: process.env.SLACK_TOKEN,
  },
});
